#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap

setxkbmap -layout jp

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

# start some nice programs
#
#if [ -d /etc/X11/xinit/xinitrc.d ] ; then
# for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#  [ -x "$f" ] && . "$f"
# done
# unset f
#fi
#
export DefaultIMModule=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS="@im=ibus"
ibus-daemon --xim &

#export DefaultIMModule='uim'
#export GTK_IM_MODULE='uim'
#export QT_IM_MODULE='uim'
#uim-xim --engine=skk &
#export XMODIFIERS='@im=uim'

unclutter --timeout 1 &
dwmblocks &
exec dwm
